CC:=gcc

fopen_fputc_fclose:fopen_fputc_fclose.c
	-$(CC) -o $@ $^
	-./$@
	-rm ./$@

fputs:fputs.c
	-$(CC) -o $@ $^
	-./$@
	-rm ./$@

fprintf:fprintf.c
	-$(CC) -o $@ $^
	-./$@
	-rm ./$@

fgetc:fgetc.c
	-$(CC) -o $@ $^
	-./$@
	-rm ./$@

fgets:fgets.c
	-$(CC) -o $@ $^
	-./$@
	-rm ./$@

fscanf:fscanf.c
	-$(CC) -o $@ $^
	-./$@
	-rm ./$@

stdin_out_err:stdin_out_err.c
	-$(CC) -o $@ $^
	-./$@
	-rm ./$@

system_call:system_call.c
	-$(CC) -o $@ $^
	-./$@
	-rm ./$@
clean:
	-rm io.txt